---
version: 2
updates:
- package-ecosystem: mpn
  directory: "/"
  schedule:
    interval: mensual
  commit-message:
    prefix: "\U0001F4CC"
  ignore:
  - dependency-name: observación*
    update-types:
    - 'actualización de versión: semver-major'
  - dependency-name: búsqueda de nodo
    update-types:
    - 'actualización de versión: semver-major'
  - dependency-name: ava
    update-types:
    - 'actualización de versión: semver-major'
  - dependency-name: regla-unificada-de-pelusa
    update-types:
    - 'actualización de versión: semver-major'
  - dependency-name: unista-*
    update-types:
    - 'actualización de versión: semver-major'
- package-ecosystem: mpn
  directory: "/funciones"
  schedule:
    interval: a diario
  commit-message:
    prefix: "\U0001F4CC(funciones)"
